import { StyleSheet,Dimensions } from "react-native";
const screenWidth = Dimensions.get("window")
import {appcolours}from "../utilities/apptheme"
    
export const appstyles = StyleSheet.create({
    bgstyles:{
        flex: 1
    },
    headerView:{
        backgroundColor:"white",
    },
    Appname:{
        fontSize:30,
        textAlign:"center",
        color:appcolours.navy,
        fontWeight:"800"

    },
    Introtext:{
        fontSize:13,
        textAlign:"center",
        color:appcolours.darkblue,
    },
    areaView:{
        display:"flex",
        backgroundColor:"white",
        justifyContent:"space-between",
        flex:1,
        marginBottom:20
    },
    getstartedView:{
        display:"flex",
        width:"100%",
        height:50,
        backgroundColor:appcolours.navy,
        alignItems:"center",
        justifyContent:"center",
        borderRadius:100
    },
    linkText:{
        color:"white",
        fontSize:20
    },
    flatimg:{
        width:screenWidth
    },
    headerView:{
        display:"flex",
        justifyContent:"center",
        alignItems:"center",
    },
    headertext:{
        fontSize:30,
        color: appcolours.navy,
        letterSpacing:4.9,
        textAlign:"center",
        fontWeight:"900",
        fontFamily:"AngelicaSignatureDemo"

    },
    designername:{
        fontSize:16,
        fontWeight:"bold",
        color:appcolours.darkblue,

    },
    iconDisply:{
        display:"flex",
        flexDirection:"row",
        gap:10
    },
    iconview:{
        display:"flex",
        flexDirection:"row",
        justifyContent:"space-between",
        alignItems:"center"
    },
    imgview:{
        height:500,
        width:screenWidth,
        paddingVertical:2
    },
    Introtext2:{
        fontSize:20,
        textAlign:"center",
        color:appcolours.darkblue,
        paddingBottom:10
    },
    // measurment styles 

    scrollcontent:{
        paddingBottom:50,
        paddingVertical:10
    },
    meaureheader:{
        marginBottom:30,
    },
    title:{
        fontSize:30,
        textAlign:"center",
        fontWeight:"800",
        color:appcolours.navy,
        fontFamily:"AvegasRoyale-Bold"
    },
    subtitle:{
        fontSize:18,
        color:appcolours.darkblue,
        textAlign:"center",
    },
    gendersection:{
        marginBottom:24,

    },
    gendertitle:{
        fontSize:15,
        fontWeight:"bold",
        color:appcolours.darkblue,
        marginBottom:12,
        textAlign:"center"
    },
    genderView:{
        display:"flex",
        flexDirection:"row",
        gap:13,
        justifyContent:"center",
        alignItems:"center",
    },
    genderbtn:{
        width:150,
        borderWidth:2,
        backgroundColor:appcolours.grey,
        borderColor:appcolours.darkblue,
        paddingVertical:12,
        borderRadius:8,
        alignItems:"center",
        justifyContent:"center"
    },
    genderbtnactive:{
        backgroundColor:appcolours.navy,
        borderColor:appcolours.red,
    },
    gendertext:{
        fontSize:15,
        fontWeight:"600",
        color:appcolours.darkblue
    },
    gendertextactive:{
         color:"white"
    },
    unitbtn:{
         width:150,
        borderWidth:2,
        backgroundColor:appcolours.grey,
        borderColor:appcolours.navy,
        paddingVertical:12,
        borderRadius:8,
        alignItems:"center",
        justifyContent:"center"
    },
    unitbtnactive:{
        backgroundColor:appcolours.navy,
        borderColor:appcolours.red,
    },
    unittext:{
        fontSize:15,
        fontWeight:"600",
        color:appcolours.darkblue 
    },
    unittextactive:{
        color:"white"
    },
    // measument inputs

    inputTitle:{
        fontSize:18,
        fontWeight:"700",
        color:appcolours.navy,
        marginBottom:8
    },
    unit:{
       fontSize:14,
       color:appcolours.navy,
       marginBottom:12 
    },
    label:{
        fontSize:16,
        fontWeight:"800",
        color:appcolours.darkblue,
        marginBottom:6
    },
    inputwrapper:{
        flexDirection:"row",
        alignItems:"center",
        borderWidth:1,
        borderColor:appcolours.grey,
        borderRadius:10,
        backgroundColor:appcolours.darkblue
    },
    section:{
        marginBottom:24,
        paddingHorizontal:20
    },
    inputfield:{
        flex:1,
        paddingVertical:12,
        paddingHorizontal:12,
        fontSize:15,
        color:"white",
        fontWeight:"400"
    },
    munit:{
        paddingRight:10
    },
    // cta styles 

     ctaview:{
        display:"flex",
         flexDirection:"row",
         justifyContent:"space-evenly",
         flex:1,

     },
     savebtn:{
        width:150,
        height:50,
        backgroundColor:appcolours.darkblue,
        borderRadius:100,
        justifyContent:"center",
        alignItems:"center",
        paddingBottom:30
     },
     resetbtn:{
        width:150,
        height:50,
        backgroundColor:appcolours.darkblue,
        borderRadius:100,
        justifyContent:"center",
        alignItems:"center",
        paddingBottom:30
     },
     ctatext:{
        color:"white",
        fontSize:17,
        fontWeight:800,
     }

})
